In [39]:
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

df = pandas.read_table('./malwareBenignScores.txt', delim_whitespace=True, header = 1,
                   dtype={'OGS': np.float64, 'HMM': np.float64, 'SSD': np.float64})


In [85]:
X0 = pd.DataFrame()
X1 = pd.DataFrame()
X0['HMM'] = df.HMM
X0['SSD'] = df.SSD
X0['OGS'] = df.OGS
X0['Score'] = 1
X1['HMM'] = df.HMM-1
X1['SSD'] = df.SSD-1
X1['OGS'] = df.OGS-1
X1['Score'] = -1
frames = [X0,X1]
X = pd.concat(frames)

Y = pd.DataFrame()
Y = X['Score']
Xtrain1 = X[0:20]
Xtrain2 = X[40:60]

framesTrain = [Xtrain1,Xtrain2]
Xtrain = pd.concat(framesTrain)

Ytrain = Xtrain['Score']
del Xtrain['Score']

In [91]:
Xtest1 = X[20:40]
Xtest2 = X[60:80]
framesTest = [Xtest1,Xtest2]
Xtest = pd.concat(framesTest)
Ytest = Xtest['Score']
del Xtest['Score']

In [98]:
lin_clf = SVC(C=1.0, kernel='poly',degree=2)
lin_clf.fit(Xtrain,Ytrain)
lin_clf.predict(Xtest)
#accuracy = 40/40 = 100%

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1])

In [99]:
lin_clf2 = SVC(C=3.0, kernel='poly',degree=2)
lin_clf2.fit(Xtrain,Ytrain)
lin_clf2.predict(Xtest)
#accuracy = 40/40 = 100%

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1])

In [100]:
lin_clf3 = SVC(C=1.0, kernel='poly',degree=4)
lin_clf3.fit(Xtrain,Ytrain)
lin_clf3.predict(Xtest)
#accuracy = 40/40 = 100%

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1])

In [101]:
lin_clf4 = SVC(C=3.0, kernel='poly',degree=4)
lin_clf4.fit(Xtrain,Ytrain)
lin_clf4.predict(Xtest)
#accuracy = 40/40 = 100%

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1])